name: cs124_pa5
channels:
  - defaults
  - pytorch
  - huggingface
  - conda-forge
dependencies:
  - jupyter=1.0.0
  - jupyter_client<7.0.0
  - nb_conda=2.2.1
  - numpy=1.22.4
  - python=3.8.5
  - matplotlib=3.5.3
  - scikit-learn=1.1.3
  - spacy=2.3.5
  - nltk=3.5
  - gensim=4.1.2
  - pytorch=2.4.1
  - transformers=4.33.3
